#!/bin/sh

#        _ _____  _____
#       | |  __ \|_   _|
#       | | |__| | | |
#   _   | |  _  /  | |
#  | |__| | | \ \ _| |_
#   \____/|_|  \_\_____|
#
# This yadm bootstrap file is launch when yadm will clone the dotfile project.
#
# The aim of this script is to perform the installation of all my dot files and so all my environment.

dir_build=~/Perso
mkdir -p ${dir_build}

cd ${dir_build} || { echo "ERROR creating repository to get sources"; exit 1; }

# ---------------------------------------------------------------------------------------------------------------------
# tmux installation
# ---------------------------------------------------------------------------------------------------------------------
# https://github.com/tmux/tmux
git clone https://github.com/tmux/tmux.git
if cd tmux; then
  # Don't forget to install all needed packages
  sudo apt install -y autoconf automake pkg-config

  sh autogen.sh
  ./configure
  make && make install
fi

# ---------------------------------------------------------------------------------------------------------------------
# fzf installation
# ---------------------------------------------------------------------------------------------------------------------
git clone --depth 1 https://github.com/junegunn/fzf.git ~/Perso/fzf
if cd ${dir_build}/fzf; then
  ./install
fi

# ---------------------------------------------------------------------------------------------------------------------
# fd installation
# ---------------------------------------------------------------------------------------------------------------------
git clone https://github.com/sharkdp/fd ~/Perso/fd
if cd fd; then
  sudo apt install -y cargo
  cargo build
  cargo test
  cargo install --path . --root ~/.local
fi

# ---------------------------------------------------------------------------------------------------------------------
# shell check installation
# ---------------------------------------------------------------------------------------------------------------------
sudo apt install -y shellcheck

# ---------------------------------------------------------------------------------------------------------------------
# Neovim installation
# ---------------------------------------------------------------------------------------------------------------------
# Curl to download the package
sudo apt install -y curl

curl -L https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb \
  -o /tmp/nvim-linux64.deb

# Change permission for apt
chmod a+x /tmp/nvim-linux64.deb
sudo apt install /tmp/nvim-linux64.deb

# Clean after work
rm -f /tmp/nvim-linux64.deb

# ---------------------------------------------------------------------------------------------------------------------
# zoxide installation
# ---------------------------------------------------------------------------------------------------------------------
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash

# ---------------------------------------------------------------------------------------------------------------------
# zoxide installation
# ---------------------------------------------------------------------------------------------------------------------
curl -sS https://starship.rs/install.sh | sh
